from __future__ import annotations

import argparse
import json
from pathlib import Path


REQUIRED_FILES = {
    "REAL_BOARD_TLS_CA_CERT_PEM": "ca.pem",
    "REAL_BOARD_TLS_CLIENT_CERT_PEM": "client.pem",
    "REAL_BOARD_TLS_CLIENT_KEY_PEM": "client.key",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed local mTLS PEM files into the real-board firmware build.")
    parser.add_argument("--cert-dir", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--tag", default="local-mtls-test")
    args = parser.parse_args()

    cert_dir = Path(args.cert_dir)
    out = Path(args.out)
    values = {}
    for symbol, filename in REQUIRED_FILES.items():
        path = cert_dir / filename
        if not path.exists():
            raise SystemExit(f"missing {filename}: {path}")
        values[symbol] = path.read_text(encoding="ascii")

    lines = [
        "/* Generated by embed_real_board_mtls_certs.py. Test certificates only. */",
        '#include "real_board_tls.h"',
        "",
        f'const char REAL_BOARD_TLS_CERT_BUNDLE_TAG[] = {json.dumps(args.tag)};',
    ]
    for symbol, text in values.items():
        lines.append(f"const char {symbol}[] = {json.dumps(text)};")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
